### PR TITLE
Adds wrapper to groups alerts

### LINKED ISSUE #15: Add wrapper to group alerts
You must log in to post replies & You must join this group to post replies.

### PR DESCRIPTION
**Pull request by PerJensen**
Fixes #15

### CODE REVIEW

**Comment by PerJensen** [comment]
Dependent on Elgg/Elgg#7389

**Comment by beck24** [comment]
Without that css does it look any different than it does currently?

**Comment by PerJensen** [comment]
Yes, here's current and without new css. The bg color is from elgg-state-notice.

before-after

**Comment by beck24** [comment]
ok that's fine.  I just didn't want to pull this in right now if it broke without that css - that would essentially make this plugin dependent on 1.10
So this is a forward-compatible non-breaking change.  All good thanks!

**Pull request merged**
